

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNavigationMenu from "@/components/MainNavigationMenu";
import { Mountain } from 'lucide-react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex items-center justify-center bg-gray-100'>
          <Mountain />
          <header style={{ padding: "1rem 0", textAlign: "center", fontSize: "2rem", fontWeight: "bold", letterSpacing: "2px" }}>
            Modular Terrain APP
          </header>
          <Mountain />
        </div>
        <MainNavigationMenu />
        {children}
      </body>
    </html>
  );
}
